// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClLKyW2SvZO0S3Y01JAeOcJ79Cn9eZnT8',
    appId: '1:907088051833:web:651e255a8ac1d78239dea8',
    messagingSenderId: '907088051833',
    projectId: 'cricai-001',
    authDomain: 'cricai-001.firebaseapp.com',
    storageBucket: 'cricai-001.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxju_UroGMRu_CFJG1p1OuQz-3LQGsgBM',
    appId: '1:907088051833:android:6ee1532e35fd3f1339dea8',
    messagingSenderId: '907088051833',
    projectId: 'cricai-001',
    storageBucket: 'cricai-001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjyCqyiZ3P_nLdZfpQ7DGCa2f-TIRdTJk',
    appId: '1:907088051833:ios:1b3ac7e95e33bd2139dea8',
    messagingSenderId: '907088051833',
    projectId: 'cricai-001',
    storageBucket: 'cricai-001.appspot.com',
    iosBundleId: 'com.example.cricai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjyCqyiZ3P_nLdZfpQ7DGCa2f-TIRdTJk',
    appId: '1:907088051833:ios:931a1ce781816ed639dea8',
    messagingSenderId: '907088051833',
    projectId: 'cricai-001',
    storageBucket: 'cricai-001.appspot.com',
    iosBundleId: 'com.example.cricai.RunnerTests',
  );
}
